# Generated by Django 5.2.3 on 2025-07-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('regex', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regex', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='placeapi.district')),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regex', models.CharField(blank=True, max_length=255)),
                ('thana_no', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('is_suggested', models.BooleanField(default=False)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions', to='placeapi.subdistrict')),
            ],
        ),
        migrations.CreateModel(
            name='SemiMetroArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regex', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_metros', to='placeapi.union')),
            ],
        ),
    ]
